/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package euler;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    // @Test public void testAppHasAGreeting() {
    //     Solution classUnderTest = new Solution();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }

    @Test
    public void addtest() {
        int a = 2;
        int b = 3;
        Solution sol = new Solution();
        assertEquals(sol.add(a,b), a+b);
    }
}
