/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {

    @Test
    public void sumMultipleTest() {
        int n = 10;
        Solution sol = new Solution();
        assertEquals(sol.sumMultiples(n), 23);
        assertEquals(sol.sumMultiples(13), 45);
    }
}
