/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// public class App {
//     public String getGreeting() {
//         return "Hello world.";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }

public class Solution {

    public int sumMultiples(int n) {
        int total = 0;
        for (int k=2; k<n; k++) {
            if (k%3==0 || k%5==0) {
                total += k;
            }
        }
        return total;
    }

    public static void main(String[] args) {
        int n = 10;
        Solution sol = new Solution();
        System.out.println("Question : " + Integer.toString(n));
        System.out.println("Answer: " + Integer.toString(sol.sumMultiples(n)));
    }
}